name: java

on: pull_request

jobs:
  unit_tests:
    name: Java Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Test
        working-directory: ./java
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
