name: mkdocs-master

on: pull_request

jobs:
  publish-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set dev version
        working-directory: ./java
        run: echo "DEV_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -Ev 'Download|INFO|WARNING')" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install deps
        working-directory: ./python
        run: cp ../README.md . && pip3 install -e .[python,dev,docs]

      - name: generate autodoc
        run: python3 auto_doc.py

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('java/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Build java doc documentation
        working-directory: ./java
        run: mvn clean install javadoc:javadoc javadoc:aggregate -DskipTests && cp -r target/site/apidocs ../docs/javadoc

      - name: setup git
        run: |
          git config --global user.name Mike
          git config --global user.email mike@docs.hopsworks.ai

      - name: mike deploy docs
        run: mike deploy ${{ env.DEV_VERSION }} dev -u
